runtime: python37
instance_class: F2
entrypoint: gunicorn server:app -t 90 --log-file -

# runtime_config:
#   python_version: 3.7

# automatic_scaling:
#   max_instances: 2
#   max_concurrent_requests: 15
#   target_cpu_utilization: 0.7


# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10


handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto