genre_replace = {'art pop':'indie',
                 'rock':'rock',
                 'dance pop':'pop',
                 'album rock':'classic rock',
                 'alternative dance':'indie',
                 'alternative rock':'rock',
                 'alternative metal':'rock',
                 'alternative r&b':'indie',
                 'bedroom pop':'indie',
                 'indie pop':'indie',
                 'chamber pop':'indie',
                 'emo':'rock',
                 'electropop':'indie',
                 'modern rock':'rock',
                 'afrofuturism':'r&b',
                 'atl hip hop':'hip hop',
                 'boy band':'pop',
                 'glam metal':'classic rock',
                 'alternative hip hop':'hip hop',
                 'garage rock':'indie',
                 'indie folk':'indie',
                 'indie garage rock':'indie',
                 'alternative country':'indie',
                 'big room':'electronic',
                 'downtempo':'indie',
                 'melodic rap':'rap',
                 'canadian contemporary r&b':'r&b',
                 'baroque pop':'indie',
                 'edm':'electronic',
                 'canadian pop':'pop',
                 'la indie':'indie',
                 'escape room':'hip hop',
                 'adult standards':'classic',
                 'austindie':'indie',
                 'dance rock':'rock',
                 'dreamo':'rock',
                 'acid rock':'classic rock',
                 'pop rap':'rap',
                 'ambient folk':'indie',
                 'brooklyn indie':'indie',
                 'australian pop':'pop',
                 'chillwave':'indie',
                 'permanent wave':'pop',
                 'electronica':'electronic',
                 'neo mellow':'r&b',
                 'candy pop':'pop',
                 'canadian hip hop':'hip hop',
                 'aussietronica':'electronic',
                 'grime':'hip hop',
                 'conscious hip hop':'hip hop',
                 'dfw rap':'rap',
                 'folk-pop':'indie',
                 'blues rock':'classic rock',
                 'electra':'electronic',
                 'alternative emo':'rock',
                 'glam rock':'rock',
                 'chamber psych':'indie',
                 'alternative americana':'indie',
                 'ambient':'ambient',
                 'britpop':'rock',
                 'irish rock':'rock',
                 'canadian indie':'indie',
                 'country rap':'rap',
                 'albuquerque indie':'indie',
                 'hard rock':'metal',
                 'english indie rock':'indie',
                 'brighton indie':'indie',
                 'modern alternative rock':'rock',
                 'french indie pop':'indie',
                 'barbadian pop':'pop',
                 'gamecore':'indie',
                 'australian psych':'indie',
                 'electro house':'electronic',
                 'canadian electropop':'indie',
                 'australian garage punk':'indie',
                 'indie cafe pop':'indie',
                 'alabama indie':'indie',
                 'edmonton indie':'indie',
                 'cali rap':'rap',
                 'british soul':'indie',
                 'electro':'electronic',
                 'dream pop':'indie',
                 'indie soul':'indie',
                 'british invasion':'classic',
                 'deep new americana':'indie',
                 'french shoegaze':'indie',
                 'disco':'disco',
                 'funk':'funk',
                 'pop':'pop',
                 'modern folk rock':'rock',
                 'brostep':'electronic',
                 'complextro':'electronic',
                 'canadian folk':'indie',
                 'indie poptimism':'indie',
                 'indie rock':'indie',
                 'houston rap':'rap',
                 'pop punk':'rock',
                 'cleveland indie':'indie',
                 'pop house':'electronic',
                 'australian dance':'pop',
                 'nc hip hop':'hip hop',
                 'k-pop':'k-pop',
                 'acoustic pop':'pop',
                 'emo rap':'rap',
                 'belgian edm':'electronic',
                 'contemporary country':'country',
                 'indie pop rap':'rap',
                 'norwegian pop':'pop',
                 'reggaeton flow':'latin',
                 'funk carioca':'funk',
                 'indie r&b':'r&b',
                 'danish electronic':'electronic',
                 'swedish gangsta rap':'rap',
                 'east coast hip hop':'hip hop',
                 'la pop':'pop',
                 'r&b en espanol':'latin',
                 'desi pop':'pop',
                 'afropop':'pop',
                 'big beat':'hip hop',
                 'baile pop':'pop',
                 'bass trap':'electronic',
                 'tropical house':'electronic',
                 'afrofuturismo brasileiro':'latin',
                 'minnesota hip hop':'hip hop',
                 'gaming edm':'electronic',
                 'deep house':'electronic',
                 'azontobeats':'hip hop',
                 'vapor soul':'electronic',
                 'turkish edm':'electronic',
                 'italian arena pop':'pop',
                 'israeli pop':'pop',
                 'colombian pop':'pop',
                 'metropopolis':'indie',
                 'hip pop':'pop',
                 'bmore':'electronic',
                 'lithuanian electronic':'electronic',
                 'hip hop':'hip hop',
                 'latin':'latin',
                 'classic rock':'classic rock',
                 'rap':'rap',
                 'reggae fusion':'reggae',
                 'reggae':'reggae',
                 'soundtrack':'soundtrack',
                 'art punk':'rock',
                 'art rock':'rock',
                 'mellow gold':'classic rock',
                 'heartland rock':'classic rock',
                 'pop rock':'pop',
                 'soft rock':'classic rock',
                 'indie':'indie',
                 'classic':'classic',
                 'country':'country',
                 'electronic':'electronic',
                 'metal':'metal',
                 'r&b':'r&b'
                 }