genre_replace = {'art pop':'indie',
                 'rock':'rock',
                 'dance pop':'pop',
                 'post-teen pop':'pop',
                 'trap':'hip hop',
                 'reggaeton':'latin',
                 'latin pop':'latin',
                 'italian disco':'disco',
                 'hip-hop/rap':'hip hop',
                 'southern hip hop':'hip hop',
                 'uk pop':'pop',
                 'post-grunge':'rock',
                 'album rock':'classic rock',
                 'alternative':'rock',
                 'alternative dance':'indie',
                 'alternative rock':'rock',
                 'alternative metal':'rock',
                 'alternative r&b':'indie',
                 'bedroom pop':'indie',
                 'indie pop':'indie',
                 'chamber pop':'indie',
                 'emo':'rock',
                 'social media pop':'pop',
                 'electropop':'indie',
                 'modern rock':'rock',
                 'afrofuturism':'r&b',
                 'atl hip hop':'hip hop',
                 'boy band':'pop',
                 'glam metal':'classic rock',
                 'alternative hip hop':'hip hop',
                 'garage rock':'indie',
                 'indie folk':'indie',
                 'indie garage rock':'indie',
                 'alternative country':'indie',
                 'big room':'electronic',
                 'downtempo':'indie',
                 'melodic rap':'rap',
                 'canadian contemporary r&b':'r&b',
                 'baroque pop':'indie',
                 'edm':'electronic',
                 'canadian pop':'pop',
                 'viral pop':'pop',
                 'german hip hop':'hip hop',
                 'la indie':'indie',
                 'rock en espanol':'latin',
                 'escape room':'hip hop',
                 'adult standards':'classic',
                 'austindie':'indie',
                 'gangster rap':'rap',
                 'underground hip hop':'hip hop',
                 'dance rock':'rock',
                 'dreamo':'rock',
                 'indietronica':'electronic',
                 'nu metal':'metal',
                 'acid rock':'classic rock',
                 'pop rap':'rap',
                 'ambient folk':'indie',
                 'brooklyn indie':'indie',
                 'australian pop':'pop',
                 'chillwave':'indie',
                 'permanent wave':'pop',
                 'electronica':'electronic',
                 'neo mellow':'r&b',
                 'candy pop':'pop',
                 'canadian hip hop':'hip hop',
                 'aussietronica':'electronic',
                 'grime':'hip hop',
                 'conscious hip hop':'hip hop',
                 'dfw rap':'rap',
                 'folk-pop':'indie',
                 'blues rock':'classic rock',
                 'electra':'electronic',
                 'alternative emo':'rock',
                 'glam rock':'rock',
                 'chamber psych':'indie',
                 'alternative americana':'indie',
                 'ambient':'ambient',
                 'britpop':'rock',
                 'irish rock':'rock',
                 'canadian indie':'indie',
                 'country rap':'rap',
                 'country road':'country',
                 'albuquerque indie':'indie',
                 'hard rock':'metal',
                 'english indie rock':'indie',
                 'brighton indie':'indie',
                 'modern alternative rock':'rock',
                 'alternative r&b':'r&b',
                 'french indie pop':'indie',
                 'barbadian pop':'pop',
                 'gamecore':'indie',
                 'australian psych':'indie',
                 'australian indie':'indie',
                 'electro house':'electronic',
                 'canadian electropop':'indie',
                 'australian garage punk':'indie',
                 'indie cafe pop':'indie',
                 'alabama indie':'indie',
                 'edmonton indie':'indie',
                 'cali rap':'rap',
                 'british soul':'indie',
                 'electro':'electronic',
                 'dream pop':'indie',
                 'indie soul':'indie',
                 'british invasion':'classic',
                 'deep new americana':'indie',
                 'french shoegaze':'indie',
                 'disco':'disco',
                 'funk':'funk',
                 'pop':'pop',
                 'modern folk rock':'rock',
                 'folk rock': 'rock',
                 'brostep':'electronic',
                 'complextro':'electronic',
                 'canadian folk':'indie',
                 'indie poptimism':'indie',
                 'indie rock':'indie',
                 'houston rap':'rap',
                 'pop punk':'rock',
                 'cleveland indie':'indie',
                 'pop house':'electronic',
                 'australian dance':'pop',
                 'nc hip hop':'hip hop',
                 'k-pop':'k-pop',
                 'acoustic pop':'pop',
                 'emo rap':'rap',
                 'belgian edm':'electronic',
                 'contemporary country':'country',
                 'indie pop rap':'rap',
                 'norwegian pop':'pop',
                 'reggaeton flow':'latin',
                 'k-rap':'rap',
                 'broadway':'pop',
                 'funk carioca':'funk',
                 'octacore':'rock',
                 'funk rock':'funk',
                 'instrumental funk':'funk',
                 'ann arbor indie':'indie',
                 'indie r&b':'r&b',
                 'danish electronic':'electronic',
                 'swedish gangsta rap':'rap',
                 'east coast hip hop':'hip hop',
                 'la pop':'pop',
                 'r&b en espanol':'latin',
                 'desi pop':'pop',
                 'afropop':'pop',
                 'big beat':'hip hop',
                 'baile pop':'pop',
                 'bass trap':'electronic',
                 'trap latino':'latin',
                 'latino':'latin',
                 'groupera':'latin',
                 'tropical house':'electronic',
                 'tropical':'electronic',
                 'afrofuturismo brasileiro':'latin',
                 'minnesota hip hop':'hip hop',
                 'gaming edm':'electronic',
                 'deep house':'electronic',
                 'azontobeats':'hip hop',
                 'vapor soul':'electronic',
                 'turkish edm':'electronic',
                 'italian arena pop':'pop',
                 'israeli pop':'pop',
                 'colombian pop':'pop',
                 'metropopolis':'indie',
                 'hip pop':'pop',
                 'bmore':'electronic',
                 'lithuanian electronic':'electronic',
                 'hip hop':'hip hop',
                 'latin':'latin',
                 'classic rock':'classic rock',
                 'rap':'rap',
                 'reggae fusion':'reggae',
                 'reggae':'reggae',
                 'soundtrack':'soundtrack',
                 'art punk':'rock',
                 'art rock':'rock',
                 'mellow gold':'classic rock',
                 'heartland rock':'classic rock',
                 'early synthpop':'electronic',
                 'pop rock':'pop',
                 'soft rock':'classic rock',
                 'indie':'indie',
                 'classic':'classic',
                 'country':'country',
                 'electronic':'electronic',
                 'metal':'metal',
                 'r&b':'r&b',
                 'r&b/soul':'r&b',
                 'hollywood':'soundtrack',
                 'background music':'ambient',
                 'jazz':'ambient',
                 'lo-fi beats':'electronic',
                 'chillhop':'electronic',
                 'classical':'classical',
                 'new wave pop':'pop',
                 'soul':'r&b',
                 'modern blues':'r&b',
                 'blues':'r&b',
                 'swedish pop':'pop',
                 'europop':'pop',
                 'urban contemporary':'hip hop',
                 'regional mexican':'latin',
                 'french hip hop':'hip hop',
                 'banda':'latin',
                 'roots rock':'classic rock',
                 'country rock':'classic rock',
                 'latin hip hop':'latin',
                 'vapor trap':'rap',
                 'stomp and holler':'indie',
                 'latin arena pop':'latin',
                 'psychedelic rock':'classic rock',
                 'singer-songwriter':'classic rock',
                 'singer-songwriter':'indie',
                 'spanish pop':'latin',
                 'progressive house':'electronic',
                 'pop edm':'electronic',
                 'new wave':'rock',
                 'neo soul':'soul',
                 'k-pop boy group':'k-pop',
                 'chicago rap':'rap',
                 'toronto rap':'rap',
                 'regional mexican pop':'latin',
                 'motown':'classic',
                 'quiet storm':'funk',
                 'progressive electro house':'electronic',
                 'miami hip hop':'hip hop',
                 'modern country rock':'country',
                 'new romantic':'rock',
                 'italian hip hop':'hip hop',
                 'piano rock':'rock',
                 'cumbia':'latin',
                 'rap metal':'metal',
                 'uk hip hop':'hip hop',
                 'philly rap':'rap',
                 'phoenix indie':'indie',
                 'hopebeat':'pop',
                 'detroit hip hop':'hip hop',
                 'dark trap':'rap',
                 'deep pop r&b':'r&b',
                 'hardcore hip hop':'hip hop',
                 'rap conscient':'rap',
                 'groove metal':'metal',
                 'new americana':'indie',
                 'west coast rap':'rap',
                 'country pop':'country',
                 'rap rock':'rap',
                 'electronic trap':'electronic',
                 'yaht rock':'classic rock',
                 'indie anthem-folk':'indie',
                 'classic soul':'classic',
                 'disco house':'electronic',
                 'k-pop girl group':'k-pop',
                 'synthpop':'rock',
                 'trap queen':'rap',
                 'freak folk':'pop',
                 'rock-and-roll':'classic',
                 'dance-punk':'electronic',
                 'protopunk':'rock',
                 'bubblegum pop':'pop',
                 'progressive rock':'rock',
                 'grunge':'rock',
                 'girl group':'pop',
                 'indie surf':'indie',
                 'dance':'electronic'
                 }